name: Done
env:
  REPO_OWNER: monali567
  REPO_NAME: APICall
  GITHUB_TOKEN: ${{ secrets.Tokens }}
on:
  repository_dispatch:
    types: [run-done]
jobs:
  done:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Done
        run: npm run done
