name: Ping
env:
  REPO_OWNER: monali567
  REPO_NAME: APICall
  GITHUB_TOKEN: ${{ secrets.Token }}
on:
  repository_dispatch:
    types: [run-ping]
jobs:
  ping:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Ping
        run: npm run ping
