name: Pong
env:
  REPO_OWNER: monali567
  REPO_NAME: APICall
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
on:
  repository_dispatch:
    types: [run-pong]
jobs:
  pong:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Run Pong
        run: npm run pong
